### ISSUE TITLE
when run on 5.13.10 kernel and use sq_poll, submit will failed with EOWNERDEAD

### ISSUE THREAD

**Issue by Sherlock-Holo** [tokio-rs/io-uring#101]
I try to run this codes
```rust
pub fn ttt() {
    let mut io_uring = IoUring::builder().setup_sqpoll(1000).build(4096).unwrap();

    let (submitter, sq, cq) = io_uring.owned_split();

    /*drop(sq);
    drop(cq);*/

    submitter.submitter().submit().unwrap();
}
```

it will failed with
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 130, kind: Uncategorized, message: "Owner died" }'

I search `io_uring EOWNERDEAD` on Google, and got somethings
[link1](https://www.spinics.net/lists/io-uring/msg08297.html)
[link2](https://lore.kernel.org/io-uring/06b764e1-adfa-dfdc-2e28-1fdfba49b970@gmail.com/T/)

**Comment by quininer** [comment]
I think this is a bug in kernel, and I have opened a issue in liburing. https://github.com/axboe/liburing/issues/413

**Comment by quininer** [comment]
This will be fixed in kernel, you can ignore it manually for now.

like

```rust
    submitter.submitter().submit()
        .or_else(|err| if err.raw_os_error() == Some(libc::EOWNERDEAD) {
            Ok(0)
        } else {
            Err(err)
        })?;
```
