### ISSUE TITLE
readme.rs fails with 'read error: -22'

### ISSUE THREAD

**Issue by cberner** [tokio-rs/io-uring#104]
I tried running the readme.rs example on Ubuntu 20.04 & Linux kernel 5.4. However, it fails with the following error:
```
thread 'main' panicked at 'read error: -22', examples/readme.rs:28:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Please let me know if additional information would be helpful

**Comment by quininer** [comment]
duplicate https://github.com/tokio-rs/io-uring/issues/87

**Comment by cberner** [comment]
Ah, that fixed it. Thanks!
