### ISSUE TITLE
0.5.2 contains break change

### ISSUE THREAD

**Issue by Sherlock-Holo** [tokio-rs/io-uring#108]
I notice the 0.5.2 version remove the ownsplit mod, it breaks program which use 0.5 version io_uring

**Comment by quininer** [comment]
It is unstable, it may be changed or deleted at any version.

**Comment by Sherlock-Holo** [comment]
ok but in docs.rs it doesn't mark it is unstable

for now if i want to share the ring like oensplit did, what is the best practice?

**Comment by quininer** [comment]
`submission_shared` and `completion_shared` have been stable, you can refer to `ownedsplit.rs` code to implement it yourself.
