### ISSUE TITLE
Why was owned split removed?

### ISSUE THREAD

**Issue by zethra** [tokio-rs/io-uring#110]
I'd like to be able to submit jobs from one thread and wait for completion on another thread. With the ownedsplit api removed there doesn't appear to be a way to do this. Is there a way I can do this or is it somehow fundamentally unsafe?

**Comment by quininer** [comment]
You can use the already stable `submission_shared` and `completion_shared` to implement owned split by yourself. see https://github.com/tokio-rs/io-uring/pull/100/files#diff-3a884378bde161d43e3099c530c5090847e826cb4501d4f7a803144e6bde14d3

**Comment by zethra** [comment]
I found a somewhat hacky way to achieve what I want with split. I'll leave the code here for future reference (and maybe so people can tell if if it's unsafe 😅)
```rust
pub(crate) struct Uring {
    pub submitter: Submitter<'static>,
    pub sq: Mutex<SubmissionQueue<'static>>,
    pub cq: Mutex<CompletionQueue<'static>>,
}
unsafe impl Send for Uring {}
unsafe impl Sync for Uring {}

static mut G: Option<IoUring> = None;

static URING: Lazy<Uring> = Lazy::new(|| unsafe {
    G = Some(IoUring::new(265).unwrap());
    let (submitter, sq, cq) = G.as_mut().unwrap().split();
    thread::spawn(move || driver::start());
    Uring {
        submitter,
        sq: Mutex::new(sq),
        cq: Mutex::new(cq),
    }
});
```

**Comment by quininer** [comment]
This seems to work, but I don't like `static mut`. It would be nice to use `submission_shared` and `completion_shared`.

**Comment by zethra** [comment]
G could probably also be a OnceCell or something but I didn't bother because it's never accessed again. Using *_shared wouldn't have an advantage to for getting the final data structure. I want the queues to be in their own locks for safety.
