### ISSUE TITLE
"cargo run --package io-uring-test" compiling failed

### ISSUE THREAD

**Issue by ShuochengWang** [tokio-rs/io-uring#115]
env: ubuntu 18.04 docker image with kernel 5.11
version: latest master
report error: 
In function io_uring_test::tests::fs::test_statx': /root/docker/ngo/deps/io-uring/io-uring-test/src/tests/fs.rs:316: undefined reference to statx'

cargo run --package io-uring-test --verbose
       Fresh cfg-if v1.0.0
       Fresh ppv-lite86 v0.2.14
       Fresh sc v0.2.5
       Fresh remove_dir_all v0.5.3
       Fresh bitflags v1.3.2
       Fresh once_cell v1.8.0
       Fresh libc v0.2.104
       Fresh anyhow v1.0.44
       Fresh getrandom v0.2.3
       Fresh socket2 v0.4.2
       Fresh io-uring v0.5.2 (/root/docker/ngo/deps/io-uring)
       Fresh rand_core v0.6.3
       Fresh rand_chacha v0.3.1
       Fresh rand v0.8.4
       Fresh tempfile v3.2.0
   Compiling io-uring-test v0.1.0 (/root/docker/ngo/deps/io-uring/io-uring-test)
     Running `rustc --crate-name io_uring_test --edition=2018 io-uring-test/src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="direct-syscall"' --cfg 'feature="unstable"' -C metadata=d272d4553a7a78d5 -C extra-filename=-d272d4553a7a78d5 --out-dir /root/docker/ngo/deps/io-uring/target/debug/deps -C incremental=/root/docker/ngo/deps/io-uring/target/debug/incremental -L dependency=/root/docker/ngo/deps/io-uring/target/debug/deps --extern anyhow=/root/docker/ngo/deps/io-uring/target/debug/deps/libanyhow-03df7f7519295bf1.rlib --extern io_uring=/root/docker/ngo/deps/io-uring/target/debug/deps/libio_uring-148994fddfe7579c.rlib --extern libc=/root/docker/ngo/deps/io-uring/target/debug/deps/liblibc-fe5c2a9ce84b0230.rlib --extern once_cell=/root/docker/ngo/deps/io-uring/target/debug/deps/libonce_cell-d408d7cbc64e2825.rlib --extern socket2=/root/docker/ngo/deps/io-uring/target/debug/deps/libsocket2-ba43a63ebf7d7564.rlib --extern tempfile=/root/docker/ngo/deps/io-uring/target/debug/deps/libtempfile-73b81ffb6941c16f.rlib`
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.10rg6ey4jushcnjz.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.11buw2icdhf1e9wf.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.13azzo52nphvyre3.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.167wiu5hoe2j7d5d.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1718gf9m1u72lrud.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.18xjnzt8b70zyqc.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.19fnwj1s73rc2ych.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1bl45m181c38wudt.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1crnc3i3vib57e.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1embazg3ibz5m2wn.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1haeyak0f0zu54tf.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1hiot7toutzex9f.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1jiym1xj8xp2x08q.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1l8tuk854u5fh99b.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1mpxd6f7d9iilmbl.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1msnen6n7xo73rsq.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1ose70rg9ca4v9pg.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1r8wnbmo6c0iz6bl.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1sw2ucu7y0j4kh8a.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1sy7x3zjips2rquu.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1t40lly2loa8orpo.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1u1haj0t1saqnntn.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1uf84cya8onw3moi.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1ufgd2nbujbqnrhx.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1utqsxz16cr55jtq.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1uvcyw19ae7qbcjc.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1v5t8a4wccc1ctgv.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1wsrtfmbtdpsh5da.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.1ybxir6lvvabioxp.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2066h7dlrcd91tpk.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.20tcscxibee517ei.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.21awdp8pkpjcyht2.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.26uv5twl2z7vz1zd.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.27m0euh1mmpkz71v.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.27mro7cbh8nwm225.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.285d8x438no5yemg.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.288hjur35gmniswo.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.288rnxw32heokgdt.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.29om3ipsghqmty0l.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2a4aqysppkcw2vc2.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2aog04uon5l8y7uw.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2bti4cit3fj7fvsq.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2d1qka8p7zi10ten.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2ddunbpqvirquvxc.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2e9fce4wch6ii1pj.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2iquwtsa8d21vdtw.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2jdomtjc39ar5dh6.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2jm1y7ygdrcfsl8p.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2l43agcc4wtsyz7d.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2m62t2m904f83eiy.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2ney289rkzr3nulz.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2nhefsskq1pt6lve.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2oudxf2z3jt35u2o.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2q6ml48y28cg88tk.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2refmzpg4wj3vsfm.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2srl63azomy1grff.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.2vjbez5htv7useg8.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.31bydzfyany7nslo.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.37y0h5q39hl0o84p.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.38kauvsguukco5dy.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.394owam6s4vjx4fj.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.398f7a9zasy0d3qs.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3afl7vdifudoheuk.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3b3yfln9it92f739.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3d3ao26lgfqugx3r.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3dfl2xv2u5de0997.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3durju2mrjufl8r.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3gq7d0nfa3gj7gke.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3iogjp2vyf7tvkre.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3jgr4j6mcmpx4ylb.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3ke5kalsik9gjqo9.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3kj4nldoacw310b0.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3lbtm70ddnxlj9oa.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3nabbemhrpqpaotu.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3p96w9e08qwryv29.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3pxmn50dz8sfjoqe.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3rlslz5t5j2i9fm6.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3t51ugsh84kl7t63.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3v6eqsm2mbkggl9c.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3xul6fkw8qntgqxn.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.3yut6z92nx95gfx8.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.43bgvlvq4mp2wa7d.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.46g8wbsp06jp4e81.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.47l3czde9w44w6fp.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.48svmwbeiy47sh21.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.4ig9aswkuseqlqgw.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.4jyxk9uatzlbue5w.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.4leyv9o9nl0vc6uf.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.4ozuy9eaec9p1qkp.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.4q9l9us1665hv3cq.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.4qq5f5qwaoki6c9.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.4rhw30ook76aa7qc.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.4ux4257g8taf2set.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.4yds6gn74ga6o6kx.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.4yvxmj4em5hqg6pu.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.50cekg6i0itm4fgn.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.52npaqtmn2e87dpj.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.53nkr7mvi5k5vq5c.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.54dgct3qralv4kli.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.55prmuhbi9dsae46.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.56b2lwzklhpcc6lc.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.58vb7s3yjrndkcli.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.5a75fwncg2dc0t13.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.5aynwu2n4viwxep1.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.5c24p010isyxz16a.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.5d848ew4ad9hg2jw.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.88jfrsydpkowuh8.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.8etng5y1891qz7k.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.9azif8fmf9m815m.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.9rrqhl0cz72g6vs.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.b5e2njunq645uom.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.cb316apf5jouom9.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.g37r5s9dne9wy09.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.lefeeg1yhr69fpl.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.m35qt5zb4qee12p.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.mzp0bw3y5stl8i9.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.pe9vchuxinz8f7a.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.tabkfec6pu48846.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.up2a8c0bwqqasg7.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.vw6q29bb0n039j9.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.wjosskognd5kvrb.rcgu.o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.zoxdx604rfdmc2o.rcgu.o" "-o" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5" "/root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.tzvjwkuqyhw9khi.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/root/docker/ngo/deps/io-uring/target/debug/deps" "-L" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/root/docker/ngo/deps/io-uring/target/debug/deps/libanyhow-03df7f7519295bf1.rlib" "/root/docker/ngo/deps/io-uring/target/debug/deps/libsocket2-ba43a63ebf7d7564.rlib" "/root/docker/ngo/deps/io-uring/target/debug/deps/libonce_cell-d408d7cbc64e2825.rlib" "/root/docker/ngo/deps/io-uring/target/debug/deps/libtempfile-73b81ffb6941c16f.rlib" "/root/docker/ngo/deps/io-uring/target/debug/deps/librand-9ef911d279e0e27f.rlib" "/root/docker/ngo/deps/io-uring/target/debug/deps/librand_chacha-582b0221d8531529.rlib" "/root/docker/ngo/deps/io-uring/target/debug/deps/libppv_lite86-f41c0abfdd1eb0b6.rlib" "/root/docker/ngo/deps/io-uring/target/debug/deps/librand_core-becd427875bb20e0.rlib" "/root/docker/ngo/deps/io-uring/target/debug/deps/libgetrandom-0bc9dc7543e3928c.rlib" "/root/docker/ngo/deps/io-uring/target/debug/deps/libremove_dir_all-b44ab79d858f6f76.rlib" "/root/docker/ngo/deps/io-uring/target/debug/deps/libcfg_if-2909e55669d95bfc.rlib" "/root/docker/ngo/deps/io-uring/target/debug/deps/libio_uring-148994fddfe7579c.rlib" "/root/docker/ngo/deps/io-uring/target/debug/deps/libsc-9ba12f5f9d59d31c.rlib" "/root/docker/ngo/deps/io-uring/target/debug/deps/liblibc-fe5c2a9ce84b0230.rlib" "/root/docker/ngo/deps/io-uring/target/debug/deps/libbitflags-2a3b432d7ce33fdc.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-3010daceac92f8fa.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-eed7c8ea6eea20e8.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-637cb1b53c807e95.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-099cf0af4375543b.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-b5f18e83369ef257.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-3bb19daa4485d5fe.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-5298ab0591e7fb29.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-1bda453aef84d106.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-1532436f783b0405.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-3d12d76f5782439f.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-87f8d20d4e058c86.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-d41f1ff31e4e0f27.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-0d5ea4f2d39b8e27.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-31288459e6a43502.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-c52e5d6301e1bd59.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-2675a9a46b5cec89.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-f51baad7bbcb81c4.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /root/docker/ngo/deps/io-uring/target/debug/deps/io_uring_test-d272d4553a7a78d5.5c24p010isyxz16a.rcgu.o: In function `io_uring_test::tests::fs::test_statx':
          /root/docker/ngo/deps/io-uring/io-uring-test/src/tests/fs.rs:316: undefined reference to `statx'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `io-uring-test`

Caused by:
  process didn't exit successfully: `rustc --crate-name io_uring_test --edition=2018 io-uring-test/src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="direct-syscall"' --cfg 'feature="unstable"' -C metadata=d272d4553a7a78d5 -C extra-filename=-d272d4553a7a78d5 --out-dir /root/docker/ngo/deps/io-uring/target/debug/deps -C incremental=/root/docker/ngo/deps/io-uring/target/debug/incremental -L dependency=/root/docker/ngo/deps/io-uring/target/debug/deps --extern anyhow=/root/docker/ngo/deps/io-uring/target/debug/deps/libanyhow-03df7f7519295bf1.rlib --extern io_uring=/root/docker/ngo/deps/io-uring/target/debug/deps/libio_uring-148994fddfe7579c.rlib --extern libc=/root/docker/ngo/deps/io-uring/target/debug/deps/liblibc-fe5c2a9ce84b0230.rlib --extern once_cell=/root/docker/ngo/deps/io-uring/target/debug/deps/libonce_cell-d408d7cbc64e2825.rlib --extern socket2=/root/docker/ngo/deps/io-uring/target/debug/deps/libsocket2-ba43a63ebf7d7564.rlib --extern tempfile=/root/docker/ngo/deps/io-uring/target/debug/deps/libtempfile-73b81ffb6941c16f.rlib` (exit code: 1)

**Comment by quininer** [comment]
Well, ubuntu 18.04 does not have this function. you can use the `--features ci` to skip this test.
