### ISSUE TITLE
Feature request: buf_group for Readv and RecvMsg

### ISSUE THREAD

**Issue by mrakh** [tokio-rs/io-uring#123]
`io_uring` supports setting `IOSQE_BUFFER_SELECT` for the `read`, `readv`, `recv` and `recvmsg` opcodes. But the library only seems to define a `buf_group` field for `Read` and `Recv`. Could `buf_group` be added to `Readv` and `RecvMsg` as well?

**Comment by quininer** [comment]
PR are welcome.

**Comment by lucab** [comment]
I think this one can be closed, it was fixed in #124.

**Comment by FrankReh** [comment]
Setting the BUFFER_SELECT is a bit non standard. It doesn't seem idiomatic to have to set the buf_group with one optional method and then the BUFFER_SELECT with an Entry flags method. But the unit test shows what's necessary.
