### ISSUE TITLE
Add support for IORING_OP_MSG_RING

### ISSUE THREAD

**Issue by newpavlov** [tokio-rs/io-uring#128]
The OP was added in Linux 5.18, see: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4f57f06ce218

**Comment by Noah-Kennedy** [comment]
I'll do this in a little bit

**Comment by lucab** [comment]
Sorry I didn't see this ticket initially, so I did add the initial logic for `IORING_OP_MSG_RING` in https://github.com/tokio-rs/io-uring/pull/170.
However there are still some bits missing, as that PR only implements the data-passing logic.
The FD-passing logic still need to be implemented, so I think this ticket can be kept open until that is done too.

**Comment by Noah-Kennedy** [comment]
If someone else wants to grab this, please do

**Comment by lucab** [comment]
I cooked up https://github.com/tokio-rs/io-uring/pull/175 for FD-sending part in the meanwhile, it is currently under review.

**Comment by lucab** [comment]
Both PRs have been merged to `master` now, I think this ticket can be closed.

**Comment by FrankReh** [comment]
Thank you @lucab! Great additions.
