### ISSUE TITLE
0.5.5 io-uring-test fails on slightly older kernels

### ISSUE THREAD

**Issue by FrankReh** [tokio-rs/io-uring#137]
The io-uring-test uses probe to look for features but with the introduction of the second sizes for the submission queue and completion queue, the test will try to setup all four combinations of ring sizes, without probing that the additional ring sizes are supported first.

If probing for this feature isn't supported before trying to use the feature, perhaps rather than a fatal error, a message indicating the test was skipped because a setup parameter was not supported would keep the entire test binary from seeming to have run into a problem?

The test runs fine on a 5.19 kernel but I ran into this on a 5.15 kernel. Certainly not a blocker - just perhaps confusing for someone else trying to use the io-uring-test package for the first time.

**Comment by quininer** [comment]
Maybe we can ignore these tests when the IoUring creation of IORING_SETUP_SQE128/IORING_SETUP_CQE32 returns an error.

Would you like to open a PR?

**Comment by FrankReh** [comment]
Should there be no output whatsoever when any setup parameter is invalid, or just for the three new test cases?

I would lean towards a solution that says the test was skipped because some setup parameters are not supported by the running kernel for any but the first test call. The first test seems to set a baseline that has been working for some time now.

I can open a PR.

**Comment by FrankReh** [comment]
It might be nice to have an extra module in io-uring that contains a function that iterates through the levels of kernel version setup flags to report in boolean form, perhaps also in string/fmt form, either what is or what is not supported for uring setup.  The 5.20 kernel is already coming with another setup flag for SINGLE_ISSUER so pretty soon, crates that depend on io-uring could benefit from a standard way to see what's possible and to either print what's possible or print what's not possible.

**Comment by FrankReh** [comment]
PR question. Would you accept a breaking change so the errno==22 for setup failure returned a new error, using Error.new()? This would allow a caller to differentiate between an invalid argument to other system calls like setting up the mmaps. But it is a breaking change.
