### ISSUE TITLE
feat: add support for multi-shot polling

### ISSUE THREAD

**Issue by saiintbrisson** [tokio-rs/io-uring#139]
Kernel `5.13` added support for multi-shot polling by setting `IORING_POLL_ADD_MULTI` in the SQE `len` field.

As per https://man.archlinux.org/man/io_uring_enter.2.en#IORING_OP_POLL_ADD:
> If IORING_POLL_ADD_MULTI is set in the SQE len field, then the poll will work in multi shot mode instead. That means it'll repatedly trigger when the requested event becomes true, and hence multiple CQEs can be generated from this single SQE. The CQE flags field will have IORING_CQE_F_MORE set on completion if the application should expect further CQE entries from the original request. If this flag isn't set on completion, then the poll request has been terminated and no further events will be generated. This mode is available since 5.13.

It would be great if this lib allowed us to enable it when using a `PollAdd` opcode. I'd love to introduce a PR implementing this, but I'm conflicted on how we would expose this to the API. Should there be another flag param for `PollAdd::new`? Add a new field? Maybe something equivalent to `Entry::flags(...)` but for `len`?

Note that there are other options using the `len` field: `IORING_POLL_UPDATE_EVENTS` and `IORING_POLL_UPDATE_USER_DATA`.

For context, there has been a proposal to create a IOSQE flag called `IOSQE_MULTI_CQES` to dismiss the need to use the `len` field, but it was rejected because only `poll` would take advantage of it.

**Comment by saiintbrisson** [comment]
I'm also guessing the feature would be gated by the `unstable` ff.

**Comment by Noah-Kennedy** [comment]
I have two thoughts here.

On one hand, I'm thinking a lot right now about how to integrate this into Tokio eventually, which pushes me towards handling this same as how tokio handles epoll: we will use this to drive readiness-based APIs under a registrations table in the driver. We could add readiness-based methods to current objects driven by this.

On the other hand, a part of me wants to expose this as some sort of stream of notification objects.

I suppose we could do both.

**Comment by saiintbrisson** [comment]
> On one hand, I'm thinking a lot right now about how to integrate this into Tokio eventually

@Noah-Kennedy  I guess Tokio could probably take advantage of `IORING_FEAT_FAST_POLL` and ignore polling sockets altogether in some cases?

**Comment by Noah-Kennedy** [comment]
Multishot recv will be huge.

**Comment by saiintbrisson** [comment]
I'd like to see something akin to sendmmsg/recvmmsg though. It's possible to mimic the behavior, but I wonder how effective would be to add support for both.

**Comment by Noah-Kennedy** [comment]
I'd agree completely. I do a lot with UDP, and sendmmsg/recvmmsg is something I feel would be really powerful here.

**Comment by saiintbrisson** [comment]
Implemented by #191.
