### ISSUE TITLE
passing operation flags: IORING_ACCEPT_MULTISHOT

### ISSUE THREAD

**Issue by FrankReh** [tokio-rs/io-uring#146]
What is the recommended way to get the IORING_ACCEPT_MULTISHOT value to pass as a flag to the opcode::Accept::new to be used by the tokio-rs/tokio-uring crate?

**Comment by FrankReh** [comment]
Now that I have it working with my own forks, I see it required adding an optional ioprio field to the Accept operation. But I'm still wondering what the preferred way to get at the constant values from the bindings should be.

**Comment by FrankReh** [comment]
@quininer How would you like this flag exposed so accept multishot can be run?

**Comment by quininer** [comment]
I don't know, if you have a prototype, I can look at it.

**Comment by FrankReh** [comment]
This issue can be closed. 

- #186 handles it.
