### ISSUE TITLE
defining some opcodes unsafe

### ISSUE THREAD

**Issue by FrankReh** [tokio-rs/io-uring#148]
I'm working on adding the opcode for registering a buf_ring and its use requires very special handling, because a buffer pointer is being given to the kernel which it then uses to write data to, on an ongoing basis, even longer than a single opcode. So I want to define the operation as unsafe so the caller gives special attention to the lifetime of the buffer.

But there is already an opcode for Connect that could have also been defined as unsafe I think https://github.com/tokio-rs/io-uring/blob/aae166577e307fd9f39d1d0401234b78b372ebb0/src/opcode.rs#L630-L651 because an address is being passed to the kernel that it at some later time accesses.

Was Connect not made unsafe because the macro couldn't be made to handle an unsafe type? Or is the thought that the whole use of io-uring is unsafe and the caller should know that going in, so there is no point in making any public functions unsafe?

I can proceed without figuring this out now, but it seems as good a time as any.
Thanks.

**Comment by Noah-Kennedy** [comment]
I think we should implement an API for this within tokio-uring which has the crate manage ownership of buffer groups.

**Comment by quininer** [comment]
opcodes are equivalent to raw pointer, it is safe to construct invalid opcode, but push to submission queue is not.

**Comment by FrankReh** [comment]
It might be that rust doesn't allow the compiler warning, like unsafe, or failure, like the borrow-checker can do, for the business of passing some addresses to the kernel that have to outlive the syscall. And then there's the question of what the trigger would be when the pointer is simply written to a ring buffer entry that is being polled with no syscall at all. Just that the lifetime of a pointer, that had been in the code a while had surprised us recently so was wondering out loud what the rust bindings could do to make the need to be careful more apparent. And as we saw, the first unit tests one thinks of don't always catch the problems.

**Comment by Noah-Kennedy** [comment]
> I think we should implement an API for this within tokio-uring which has the crate manage ownership of buffer groups.

I forgot which repository we were in when I said this, and thought that you were asking for an unsafe raw opcodes API in tokio-uring.
