### ISSUE TITLE
direct-syscall feature doesn't report errors correctly

### ISSUE THREAD

**Issue by aidanhs** [tokio-rs/io-uring#154]
Linux syscalls do not set errno directly - libc is responsible for taking negative return values from the syscall return value and populating errno.

This means that anything depending on errno (like `std::io::Error::last_os_error()`) will not work if you're not using libc.

When using direct-syscall, libc is not used in the `sys` module - so any call to `sys::*` followed by a `last_os_error` will not report errors correctly. One example of this is when calling io_uring_setup https://github.com/tokio-rs/io-uring/blob/6c535d2ce8d05f7a5eb33a82d948e6eb7e19c6f7/src/lib.rs#L175-L182

Cargo.toml
```
[package]
name = "ringer"
version = "0.1.0"
edition = "2021"
[dependencies]
io-uring = { version = "0.5", features = ["direct-syscall"] }
```

src/main.rs
```
fn main() {
    io_uring::IoUring::new(u32::MAX).unwrap();
}
```

Output from `cargo run`:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 0, kind: Uncategorized, message: "Success" }', src/main.rs:2:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If you remove the `direct-syscall` feature you instead get:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', src/main.rs:2:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

You can fix this by handling the conversion yourself, but an alternative is to move from `sc` to https://crates.io/crates/rustix which already does this conversion into its own `io::Result` type - e.g. https://docs.rs/rustix/latest/rustix/io_uring/fn.io_uring_enter.html returns a `rustix::io::Result` (which you can convert this into a `std::io::Result` with `res.map_err(std::io::Error::from)`)

**Comment by aidanhs** [comment]
I see three places where this is handled incorrectly:

https://github.com/tokio-rs/io-uring/blob/6c535d2ce8d05f7a5eb33a82d948e6eb7e19c6f7/src/lib.rs#L175-L182

https://github.com/tokio-rs/io-uring/blob/6c535d2ce8d05f7a5eb33a82d948e6eb7e19c6f7/src/register.rs#L15-L20

https://github.com/tokio-rs/io-uring/blob/6c535d2ce8d05f7a5eb33a82d948e6eb7e19c6f7/src/submit.rs#L96-L110

The last one is interesting because it is *trying* to do the right thing, but I think it's subtly wrong - if a syscall returns EPERM (mapped to -1) then this code will incorrectly believe it's a libc return value and call `last_os_error` and probably get nonsense.

(fortunately `io_uring_enter` isn't documented to return `EPERM` so this is more a theoretical problem in this case)

**Comment by quininer** [comment]
You are right, I am actually known this problem. rustix is a pretty big dependency and I would rather avoid it. Also direct-syscall doesn't seem to be really used by anyone and I've been considering remove it in next release.

**Comment by aidanhs** [comment]
Ah! I'm currently starting to use it, and in fact looking at building on it to allow `no_std` - but if it's a maintenance burden then it's fair to remove.

**Comment by quininer** [comment]
If you use it, I would be happy to accept a PR for the fix. :D
