### ISSUE TITLE
feature request: API to set file_index

### ISSUE THREAD

**Issue by boohba** [tokio-rs/io-uring#158]
![image](https://user-images.githubusercontent.com/58115165/202893957-1cb4ae25-5cad-40a0-a98b-b1be195ab935.png)
I will be more than happy to contribute.

**Comment by FrankReh** [comment]
@quininer This sounds reasonable, doesn't it? Can you give the go ahead to offer a PR?

**Comment by quininer** [comment]
Please feel free to open a PR.

**Comment by lucab** [comment]
I think this one is in fact a duplicate of https://github.com/tokio-rs/io-uring/issues/178, see the list of relevant opcodes there. All relevant ones should be fixed now.
