### ISSUE TITLE
Not all operations taking a file descriptor accept a Fixed file slot

### ISSUE THREAD

**Issue by FrankReh** [tokio-rs/io-uring#177]
Why don't all operations that are mapped to uring operations take a possible Fixed slot argument as their fd parameter?

One example is `statx` but there are many.

**Comment by quininer** [comment]
This is because not all opcode accept Fixed. For example `statx` https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/io_uring/statx.c?h=v6.1.9#n30

**Comment by FrankReh** [comment]
Well, that's a good reason. Thanks for pointing out the line, that helped. I've gone through the kernel device source and here's the list that don't accept it.

- renameat
- unlinkat
- mkdirat
- symlinkat
- linkat
- statx
- close (the normal uring close - there is a close_direct that is supported but it doesn't take a flag, it uses the file_index field)
- getxattr
- setxattr
