### ISSUE TITLE
What parameter to define for the opcode::close optional file_index?

### ISSUE THREAD

**Issue by FrankReh** [tokio-rs/io-uring#182]
@quininer @lucab I would like to add the ability to close a fixed file table entry. If I follow the model created by #179, the API will allow a value representing auto. I can go with that for now. It will compile and work and if the user uses the auto function to create the entry by accident, they'll get a runtime error that the index was out of range. Is that okay? I can provide a warning in the function's comment section to that effect.

**Comment by lucab** [comment]
It is my understanding that `IORING_OP_CLOSE` only takes FDs/fixed-files as inputs, so I think that following #179 for this one is not a good idea (the approach there is is ok fixed-file outputs).

I think prior art in this library points towards using the `UseFixed` sealed trait :
https://github.com/tokio-rs/io-uring/blob/dcf6a124926cfb32bc94ff0b617bba6844bf54b6/src/types.rs#L17-L19

That would allow internally matching on the two variants:
https://github.com/tokio-rs/io-uring/blob/dcf6a124926cfb32bc94ff0b617bba6844bf54b6/src/types.rs#L7-L11

Overall the `close` operation looks a bit similar to `fsync`, which is currently implemented this way:
https://github.com/tokio-rs/io-uring/blob/dcf6a124926cfb32bc94ff0b617bba6844bf54b6/src/opcode.rs#L221-L229

**Comment by FrankReh** [comment]
@lucab I agree with you. I'm happy to change what I wrote in #181 yesterday to follow this line of reasoning if @quininer agrees this would be better.

The internal logic to opcode::Close would be different than how other functions have use the sealed fixed parameter but that's an easy technicality.

**Comment by FrankReh** [comment]
Done. It's better with the `UseFixed` trait.
