### ISSUE TITLE
opcode::Recv , buf_group and multi question

### ISSUE THREAD

**Issue by FrankReh** [tokio-rs/io-uring#194]
@quininer 

I see opcode::Recv has had the ability to use a fixed buffer by passing an optional buf_index argument but also having to set Entry flags with the BUFFER_SELECT bit. For some years now.

And the RecvMulti I submitted and had merged a few days ago uses the same code sys::IORING_OP_RECV.

I don't really see a good way of combining both opcode::Recv and code::RecvMulti into one opcode. And you probably don't want to change the API for the buf_group flag that has existed for opcode::Recv anyway.

But the opcode::SendZc, being modified to take an Option\<u16> for buf_index in the 193 PR is following a different route.

I don't even know how you knew the io_uring recv takes a buf_index optionally. It's not in their man page. But the unit test does seem to work so it's probably correct.

So maybe nothing needs to be changed. But if you had a suggestion, I could try to make it work out in the next day or two.

**Comment by quininer** [comment]
I don't think `Recv` and `RecvMulti` need to be combined because they require different necessary parameters.

`SendZc` is a different case, `Read` and `ReadFixed` are split just because they are different opcodes, but `buf_index` parameter itself is optional. I think it's a legacy design of kernel io_uring.

**Comment by FrankReh** [comment]
Okay. Makes sense. Maybe I'll add something to the Recv doc to show how to use it for a fixed buffer after checking with the kernel source or liburing team about why Recv supports it but it doesn't get mentioned in the man pages.
