### ISSUE TITLE
OpenAt does not work with IOPOLL feature

### ISSUE THREAD

**Issue by lizhanhui** [tokio-rs/io-uring#199]
Hi, we are buiding a data-intensive application on top of I/O Uring. Our IO threads are following thread-per-core paradigm, which reuiqres all IO ops are async.  Also, we are using IOPOLL feature to avoid context switches.

We then find out that once IOPOLL feature is enabled, OpenAt would crash the process.

Here is a sample code that can reproduce the issue with latest io-uring crate(v0.5.12):
```
use std::{error::Error, ffi::CString};

use io_uring::{opcode, register, types, IoUring};

fn main() -> Result<(), Box<dyn Error>> {
    let mut uring = IoUring::builder()
        .dontfork()
        .setup_iopoll() // Commenting out this line to disable feature: IOPOLL will fixes core dump issue. 
        .setup_sqpoll(2000)
        .setup_sqpoll_cpu(1)
        .setup_r_disabled()
        .build(1024)?;

    let mut probe = register::Probe::new();
    uring.submitter().register_probe(&mut probe)?;
    uring.submitter().register_iowq_max_workers(&mut [2, 2])?;
    uring.submitter().register_enable_rings()?;

    let file_name = "/tmp/sample.txt".to_string();

    if !probe.is_supported(opcode::OpenAt::CODE) {
        eprintln!("OpenAt is not supported");
        return Ok(());
    }

    let sqe = opcode::OpenAt::new(types::Fd(libc::AT_FDCWD), file_name.as_ptr() as *const i8)
        .flags(libc::O_CREAT | libc::O_RDWR | libc::O_DIRECT)
        .mode(libc::S_IRWXU | libc::S_IRWXG)
        .build()
        .user_data(1);

    unsafe { uring.submission().push(&sqe)? };

    uring.submit_and_wait(1)?;

    let mut cq = uring.completion();
    if let Some(cqe) = cq.next() {
        println!("{cqe:#?}");
        if cqe.result() < 0 {
            let ptr = unsafe { libc::strerror(-cqe.result()) };
            match unsafe { CString::from_raw(ptr) }.into_string() {
                Ok(s) => {
                    eprintln!("{}", s);
                }
                Err(e) => {
                    eprintln!("Failed to convert CString to String: {:?}", e);
                }
            };
        }
    }
    cq.sync();

    Ok(())
}

```

Crash output are:
```
Entry {
    result: -22,
    user_data: 1,
    flags: 0,
}
Invalid argument
munmap_chunk(): invalid pointer
Aborted (core dumped)
```
OS/Kernel info:
```
ubuntu@ip-172-31-39-78:/data/elastic-storage$ uname -a
Linux ip-172-31-39-78 5.15.0-1028-aws #32-Ubuntu SMP Mon Jan 9 12:28:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by FrankReh** [comment]
So the io_uring command doesn't really crash does it? Isn't what you are seeing is an abort from the line trying to print what you created without unsafe code? When you don't use iopoll, the cqe result is probably zero. When you do use iopoll, the io_uring device is telling you there was something invalid about the request, so it is returning -22, that's -EINVAL.

So the crash here maybe that you are misusing unsafe, libc or it's ability to create a string at line 40.

And why is the io_uring instance returning the EINVAL error for your openat?

Maybe you aren't providing the environment that iopoll needs. It seems pretty specific. From the io_uring_setup(2)

       IORING_SETUP_IOPOLL
              Perform busy-waiting for an I/O completion, as opposed to getting notifi‐
              cations via an asynchronous IRQ (Interrupt Request).  The file system (if
              any) and block device must support polling in order  for  this  to  work.
              Busy-waiting  provides  lower latency, but may consume more CPU resources
              than interrupt driven I/O.  Currently, this feature is usable only  on  a
              file  descriptor opened using the O_DIRECT flag.  When a read or write is
              submitted to a polled context, the application must poll for  completions
              on  the  CQ  ring by calling io_uring_enter(2).  It is illegal to mix and
              match polled and non-polled I/O on an io_uring instance.

              This is only applicable for storage devices for now, and the storage  de‐
              vice must be configured for polling. How to do that depends on the device
              type in question. For NVMe devices, the nvme driver must be  loaded  with
              the  poll_queues  parameter  set to the desired number of polling queues.
              The polling queues will be shared appropriately between the CPUs  in  the
              system, if the number is less than the number of online CPU threads.

**Comment by FrankReh** [comment]
Here's a working version that doesn't abort. I looked into CStr vs CString.

```rust

use std::{error::Error, ffi::CStr};

use io_uring::{opcode, register, types, IoUring};

fn main() -> Result<(), Box<dyn Error>> {
    let mut uring = IoUring::builder()
        .dontfork()
        .setup_iopoll() // Commenting out this line to disable feature: IOPOLL will fixes core dump issue. 
        .setup_sqpoll(2000)
        .setup_sqpoll_cpu(1)
        .setup_r_disabled()
        .build(1024)?;

    let mut probe = register::Probe::new();
    uring.submitter().register_probe(&mut probe)?;
    uring.submitter().register_iowq_max_workers(&mut [2, 2])?;
    uring.submitter().register_enable_rings()?;

    let file_name = "/tmp/sample.txt".to_string();

    if !probe.is_supported(opcode::OpenAt::CODE) {
        eprintln!("OpenAt is not supported");
        return Ok(());
    }

    let sqe = opcode::OpenAt::new(types::Fd(libc::AT_FDCWD), file_name.as_ptr() as *const i8)
        .flags(libc::O_CREAT | libc::O_RDWR | libc::O_DIRECT)
        .mode(libc::S_IRWXU | libc::S_IRWXG)
        .build()
        .user_data(1);

    unsafe { uring.submission().push(&sqe)? };

    uring.submit_and_wait(1)?;

    let mut cq = uring.completion();
    if let Some(cqe) = cq.next() {
        println!("{cqe:#?}");
        if cqe.result() < 0 {
            let ptr = unsafe { libc::strerror(-cqe.result()) };

            // From https://stackoverflow.com/questions/24145823/how-do-i-convert-a-c-string-into-a-rust-string-and-back-via-ffi
            let c_str: &CStr = unsafe { CStr::from_ptr(ptr) };
            let str_slice: &str = c_str.to_str().unwrap();
            let str_buf: String = str_slice.to_owned();
            eprintln!("reported error: {}", str_buf);
        }
    }
    cq.sync();

    Ok(())
}
```
results in
```
Entry {
    result: -22,
    user_data: 1,
    flags: 0,
}
reported error: Invalid argument
```

If this answers your question, would you mind changing the title of the issue so future readers don't think IOPOLL or OpenAt causes crashes - if you agree?

Good luck with monoio. It's interesting.

**Comment by lizhanhui** [comment]
Thanks @FrankReh I see the cause of crash. 

```
 Currently, this feature is usable only  on  a file  descriptor opened using the O_DIRECT flag.
```

We do not have a FD yet. So things won't work in this way.

**Comment by FrankReh** [comment]
> Thanks @FrankReh I see the cause of crash.
> 
> ```
>  Currently, this feature is usable only  on  a file  descriptor opened using the O_DIRECT flag.
> ```
> 
> We do not have a FD yet. So things won't work in this way.

i want to make sure you see there were two problems. Your crash was caused by your incorrect use of CString.

Only your returned result was caused by using IOPOLL incorrectly. I'm going to change the title a little bit more.

**Comment by lizhanhui** [comment]
It's true the core dump is caused by the incorrect use of CString. But the core part of this issue is that I/O Uring is pretty restricted when IOPOLL is involved, even if all ops are device-related. 

If you do not mind, IMHO, keeping OpenAT, IOPOLL incompatible info in the title might be helpful to other developers.

**Comment by FrankReh** [comment]
Okay. Please rename it. But don't put *crash* in the title. In the future, I would recommend ascertaining the line the stack trace indicates is crashing, or use println's to figure it out. Also I would recommend just printing the result integer, no need to see a string at all. It's easy to look up what errno 22 means. 

Are you going to make it something to the effect that IOPOLL only works on files opened with O_DIRECT?

**Comment by lizhanhui** [comment]
> Are you going to make it something to the effect that IOPOLL only works on files opened with O_DIRECT?

Yes, as a specific example of `Currently, this feature is usable only  on  a file  descriptor opened using the O_DIRECT flag.`

One more thing, though it is not the right place, `errno 22 Invalid argument` is less accurate than `errno 95 Operation not supported` in this context.

**Comment by FrankReh** [comment]
> One more thing, though it is not the right place, `errno 22 Invalid argument` is less accurate than `errno 95 Operation not supported` in this context.

Oh, maybe you haven't dug into where that error comes from. This crate, `io-uring` does not generate that. It comes from the driver in the Linux kernel. Maybe that's why you think people will come to this crate to learn what can or can't be done. This isn't the crate setting those rules. The actual functionality is added to the kernel by a team that also supports a C library, `liburing`.

If you think someone will change the errno code for this situation, it is that team you should be addressing, not this one.

**Comment by lizhanhui** [comment]
Thanks for your reply, but take it easy... Already said `though it is not the right place`, just stating the fact uring/liburing is not picking up the most accurate error number.
