### ISSUE TITLE
Is it possible to use opcode::Accept with types::Fixed?

### ISSUE THREAD

**Issue by redbaron** [tokio-rs/io-uring#204]
on the type level `opcode::Accept` supports `types::Fixed` as fd, but how to actually use one? To accept connection `listen(2)` must be called on it, but how to do that on a fixed fd? My understanding is that they are private to uring and not usable in normal syscalls.

**Comment by fathyb** [comment]
I'm doing it by using normal syscalls to create the fd and listen and then register it either:
- synchronously using `self.ring.submitter().register_files_update(id, &[fd])`
- asynchronously using `opcode::FilesUpdate::new(fd as _, 1).offset(id).build()`

**Comment by saiintbrisson** [comment]
Expanding on @fathyb's answer, you may even use TcpListener if you wish:

```rust
let listener = TcpListener::bind("0.0.0.0:80").unwrap(); // or do so with socket2
let fd_idx = 0;
submitter.register_files_update(fd_idx, &[listener.into_raw_fd()]).unwrap();
```

**Comment by redbaron** [comment]
That explains it, thanks!
