### ISSUE TITLE
feature wanted: io_uring_submit_and_wait_timeout

### ISSUE THREAD

**Issue by glenn-wang** [tokio-rs/io-uring#206]
As the title, could support io_uring_submit_and_wait_timeout ?

https://github.com/axboe/liburing/blob/liburing-2.3/src/queue.c#L317

**Comment by tisonkun** [comment]
+1 otherwise how can we proactive break a wait?

**Comment by saiintbrisson** [comment]
Hi! It does already through [`Submitter::submit_with_args`](https://docs.rs/io-uring/0.6.1/io_uring/struct.Submitter.html#method.submit_with_args)

Example usage:
```rust
let want = 10;

let timespec = types::Timespec::new().sec(1).nsec(500);
let args = types::SubmitArgs::new().timespec(&timespec);

submitter.submit_with_args(10, &args).expect("failed to submit");
```
