### ISSUE TITLE
Building with bindgen feature fails with recent kernel headers.

### ISSUE THREAD

**Issue by plugwash** [tokio-rs/io-uring#238]
When I run "cargo test --all --all-targets --features bindgen" in a Debian sid environment I get.

    error[E0560]: struct `io_uring_buf_reg` has no field named `pad`
       --> src/submit.rs:444:13
        |
    444 |             pad: 0,
        |             ^^^ `io_uring_buf_reg` does not have this field
        |
        = note: available fields are: `ring_addr`, `ring_entries`, `bgid`, `flags`, `resv`
    
    error[E0560]: struct `io_uring_buf_reg` has no field named `pad`
       --> src/submit.rs:464:13
        |
    464 |             pad: 0,
       |             ^^^ `io_uring_buf_reg` does not have this field
       |
       = note: available fields are: `ring_addr`, `ring_entries`, `bgid`, `flags`, `resv`
    
    For more information about this error, try `rustc --explain E0560`.

From some googling It looks like since linux 6.3 the field has been renamed from "pad" to "flags".

**Comment by quininer** [comment]
Fix by 0.6.1
