### ISSUE TITLE
`ReadFixed` and `WriteFixed` descriptions

### ISSUE THREAD

**Issue by Connortsui20** [tokio-rs/io-uring#275]
https://docs.rs/io-uring/latest/io_uring/opcode/struct.ReadFixed.html
> Read from pre-mapped buffers that have been previously registered...

Should this be "Read _into_ pre-mapped buffers" instead of "Read _from_"?

https://docs.rs/io-uring/latest/io_uring/opcode/struct.WriteFixed.html
> Write to pre-mapped buffers that have been previously registered...

Also, should this be "Write _from_ pre-mapped buffers" instead of "Write _to_"?

I'm pretty sure this is the case, but not 100% sure.

**Comment by quininer** [comment]
You are right, would you like to open a PR to fix it?

**Comment by Connortsui20** [comment]
Sure!

It would probably be good for me to take the time to add some more specific documentation that isn't just pointing to man pages. Hopefully I can get those done next month (when my school semester has finished)
