### ISSUE TITLE
how to let `submit_and_wait` to wait for a new entry

### ISSUE THREAD

**Issue by Sherlock-Holo** [tokio-rs/io-uring#28]
with concurrent IoUring, I create a thread and it will call `submit_and_wait(1)` to waiting for the entry, when it is waiting, I create another thread and push a new entry into sqe. but the thread one doesn't know a new entry is pushed.

How to let `submit_and_wait` know a new entry is pushed and return it when it ready? I've tried to call `submit` after push, it works with `Readv` and `Writev`, the `submit_and_wait` return after read or write complete, but `Openat2` doesn't work, the `submit_and_wait` still blocking even the file is created.

Is there a better way to do this?

**Comment by quininer** [comment]
> but Openat2 doesn't work, the submit_and_wait still blocking even the file is created.

I failed to reproduce this problem. can you share your code?

**Comment by Sherlock-Holo** [comment]
open_options.rs: https://fars.ee/0plu/
lib.rs: https://fars.ee/JV4i/
ext.rs: https://fars.ee/Kguw/
Cargo.toml https://fars.ee/xXlP/

the `tests::open` run won't finish because `ring.submit_and_wait(1).unwrap();` never return

other tests work well

**Comment by Sherlock-Holo** [comment]
run cargo test with `--nocapture`, the `tests::open` will print some log like

> ```
>     Finished test [unoptimized + debuginfo] target(s) in 0.07s
>      Running target/debug/deps/ring_io-100c7598fff98b7a
> 
> running 1 test
> dir path "/tmp/.tmpLlv2mk"
> file path "/tmp/.tmpLlv2mk/test"
> start create file
> pushed
> submited
> ```

if `submit_and_wait` return, it should print log **wait done**

**Comment by quininer** [comment]
You forgot to call `run_ring` in `OpenFuture`, which caused `submit_and_wait` not to be called at all.

**Comment by Sherlock-Holo** [comment]
oh.... thank you to point my mistake 🤣. after call it, the `tests::open` works well now, problem solved
