### ISSUE TITLE
fail to compile when using musl

### ISSUE THREAD

**Issue by win-t** [tokio-rs/io-uring#29]
I'm using v0.3.5 and alpine linux

here is the errors message
```
   Compiling io-uring v0.3.5
error[E0412]: cannot find type `statx` in crate `libc`
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/io-uring-0.3.5/src/opcode.rs:750:30
    |
750 |         statxbuf: *mut libc::statx,
    |                              ^^^^^ help: a struct with a similar name exists: `stat`
    | 
   ::: /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.69/src/macros.rs:79:13
    |
79  |             pub struct $i { $($field)* }
    |             ------------- similarly named struct `stat` defined here

error: aborting due to previous error
```

here is musl version
```
$ apk info musl
musl-1.1.24-r2 description:
the musl c library (libc) implementation

musl-1.1.24-r2 webpage:
https://musl.libc.org/

musl-1.1.24-r2 installed size:
614400
```

**Comment by quininer** [comment]
musl does not provide `statx` struct in header file... this is tricky, I want to have a linux crate to provide linux header binding, but there is currently no such crate.

I think it is best to provide an opaque type, users need to cast it. but any change will be a break change, so I will keep it to next version.

**Comment by sboeuf** [comment]
@quininer did you make any progress on this issue? And when is the release date for 0.4?

**Comment by quininer** [comment]
I plan to have some major API changes in 0.4, but I don't have time to complete it at the moment. If you need it, I don't mind delaying it to 0.5, and 0.4 will be released this weekend.

**Comment by sboeuf** [comment]
>If you need it, I don't mind delaying it to 0.5, and 0.4 will be released this weekend.

That'd be really useful yes :+1: 

>I plan to have some major API changes

What kind of changes are you expecting?

**Comment by quininer** [comment]
> What kind of changes are you expecting?

I am a little dissatisfied with opcode, but I checked it just now and it seems that it will not change much. I will try to make it catch up to 0.4.

**Comment by quininer** [comment]
I have made 0.4 branch, but I don't have a good idea about #27, so I decided to postpone the 0.4 release to next week.

**Comment by sboeuf** [comment]
@quininer thanks for releasing 0.4 along with the fix for musl!
Are you planning on propagating this release to `crates.io`, or should I simply rely on the crate through git?

**Comment by quininer** [comment]
@sboeuf  This version broke the test and I haven't fixed it yet. I will publish to `crates.io` on weekend.

Currently you can use it by specifying git, but please note that some parameters of opcode may still change.

**Comment by sboeuf** [comment]
Alright!

**Comment by quininer** [comment]
@sboeuf 0.4.0 has been released.

**Comment by sboeuf** [comment]
Thanks for the heads up @quininer
