### ISSUE TITLE
CI Test

### ISSUE THREAD

**Issue by quininer** [tokio-rs/io-uring#3]

**Comment by quininer** [comment]
I don't know of any ci that supports linux 5.3, so I can only run tests locally.

**Comment by quininer** [comment]
We should at least use cargo check to ensure it compiles on expected platform.

**Comment by LucioFranco** [comment]
Is docker an option here?

**Comment by quininer** [comment]
Docker don't actually deal with kernels, but we might be able to use qemu to run the specified kernels like [cross](https://github.com/rust-embedded/cross/blob/master/docker/linux-image.sh#L8).

**Comment by Xuanwo** [comment]
Maybe we can use github action for CI tests:

- github actions supports [ubuntu 20.04](https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners)
- and ubuntu 20.04 uses [kernel 5.4](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md)

**Comment by quininer** [comment]
This is fine, but linux 5.4 is a bit too old.

we need to refactor test make it can run on different kernel versions .
