### ISSUE TITLE
Why not use CAS in loom ringbuf?

### ISSUE THREAD

**Issue by soro** [tokio-rs/io-uring#35]
https://github.com/tokio-rs/io-uring/blob/29ae5cbc7341c1250093226b6b236afa427a6cbc/loom-ringbuf/ring.rs#L33

I was just wondering why you chose to use a lock instead of casing tail?

**Comment by quininer** [comment]
The design of linux io-uring does not allow us to push entry into ringbuf concurrently, so there is not difference between cas and spinlock.

I did use cas initially, but then switched to mutex.

**Comment by soro** [comment]
Ah, because the kernel polls on the tail unless you use the io_uring_enter thing.. Well, there still is a way to update the ring buffer concurrently, it just requires extra work. Not sure if it would even end up faster at that point, but who knows. If you use an auxiliary buffer of the same size that tracks completion of the store, you can, for every write, simply set the io_uring tail to the highest contiguous position in the auxiliary buffer that has its slot set to true and then update the head on the auxiliary buffer.

**Comment by soro** [comment]
Maybe I'll get around to it. Just close the issue for now. If I do try it out I'll open PR
