### ISSUE TITLE
Use PhantomPinned to get !Unpin on ring types

### ISSUE THREAD

**Issue by dekellum** [tokio-rs/io-uring#40]
I've started a prototype, using this crate and eventfd, to try an implement efficent async file-backed `Stream` and `Sink` types.  In review, I noticed this comment on `IoUring`:

https://github.com/tokio-rs/io-uring/blob/56531043ad78e38b1f27986d175b8d961112d3a4/src/lib.rs#L72

Given the self-referential nature, should `SubmissionQueue`, `CompletionQueue`, and `IoUring` use `PhantomPinnned`? As far as I can tell at present they all implement `Unpin`, automatically.  Or is this not relevant because these types don't own memory buffers, just contain pointers to memory mapped regions that won't be moved?   If the latter, then it might be possible to say something more assuring in place of the current comment? Thanks!

**Comment by quininer** [comment]
I think it is latter, and I will add some comment. Thank you.
