### ISSUE TITLE
release 0.5 or 0.5-alpha.1 ?

### ISSUE THREAD

**Issue by miquels** [tokio-rs/io-uring#42]
The git log says " release 0.5.0-alpha" but it's not on crates.io. In the mean time, the repository has moved to a new home. Would you consider releasing an -alpha or -alpha.1 to crates.io so that we can have the latest (admittedy small) fixes, and so that crates.io points to the correct repo ?

Thanks for this crate btw. I'm just playing around with io_uring but I'm glad I did not have to mess around with the C liburing or  raw system calls.

**Comment by quininer** [comment]
Okay, I will release the new version tonight.

**Comment by quininer** [comment]
0.5.0-alpha has been released
