### ISSUE TITLE
Remove concurrent module ?

### ISSUE THREAD

**Issue by quininer** [tokio-rs/io-uring#46]
In practice, concurrent sq is useful, while concurrent cq is almost useless. we can split the two and provide concurrent sq and non-concurrent cq to avoid some atomic overhead.

And, I hope to implement lock-free squeue.

**Comment by Koxiaet** [comment]
I have an idea for how to remove the lock in the concurrent sqe. It still involves waiting, but it should be slightly cheaper. We store a second tail atomic, `reserved_tail`, that stores the ring buffer index up to which there are entries reserved. To push to the sq, threads will:

1. Increment `reserved_tail` atomically.
2. Write their entries to the slots that have been reserved.
3. While attempting to CAS `tail` from the old value of `reserved_tail` to the new value of `reserved_tail` fails, wait on `head`'s futex.
4. Wake `head`'s futex.

Would this work?

**Comment by quininer** [comment]
@Koxiaet  It sounds good, maybe the performance will be better than the lock under light load.

Would you like to try it?

**Comment by Koxiaet** [comment]
@quininer Yes, I'll see if I can implement it.
