### ISSUE TITLE
Return Error EBADF when enable setup_sqpoll

### ISSUE THREAD

**Issue by sunyulin728** [tokio-rs/io-uring#48]
When enable setup_sqpoll, if run the writev request, it will return -9 (EBADF). 
There is no such issue to disable the sqpoll.

**Comment by quininer** [comment]
> To successfully use this feature, the application must register a set of files to be used for IO through io_uring_register(2) using the IORING_REGISTER_FILES opcode. Failure to do so will result in submitted IO being errored with EBADF.

Maybe you are not using the registered file?

**Comment by sunyulin728** [comment]
Yes. You are right. It works with fixed file.
