### ISSUE TITLE
Example echo server different behavior in different systems

### ISSUE THREAD

**Issue by JeepYiheihou** [tokio-rs/io-uring#51]
A pretty weird problem (to me).

**Symptom**

By learning this io_uring library, I started from trying out the echo server code in example. The code is here:
https://github.com/JeepYiheihou/rust-io-uring-echo-server

However the behavior is different on two of my machines. One unexpected and another one expected.

The unexpected one happens on my fedora machine. It only returns contents after 3 lines of your input, and returns them altogether:

```
[jiachenbai@localhost 23:10:18 io_uring-echo-server]$ telnet 127.0.0.1 3456
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
a
b
c
a
b
c
```

And the expected one happens on my ubuntu machine. This time it runs well:
```
jiachen@jiachen-dev:~/workspace/rust/echo-server$ telnet localhost 3456
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
a
a
b
b
c
c
```
**Investigation**
I suspected it might be the problem with kernel's io_uring functionality, but I tried some other echo servers in C implemetation, for example https://github.com/frevib/io_uring-echo-server, but they work consistently on both systems.

To follow up with a previous discussion before in the email, the echo server is submitting sqe with opcode `IORING_OP_READV`, which should trigger the kernel to perform a `preadv` call. However, if I understand correctly, a preadv doesn't wait until the buffer is filled up. It just returns whatever it reads and it only blocks & waits when the socket is really empty. (The system call that really waits untill buffer is full should be `recv` if I'm right. Please correct me.) So in this regard, the echo server even betrays the behavior of the system call under the hood. To make things more weird, the server just returns every 3 times, regardless how many chars you type in each time. Look at this:
```
[jiachenbai@localhost 23:26:36 io_uring-echo-server]$ telnet 127.0.0.1 3456
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
a looong string      
an even loooooonger string
a verrrrrrrrry looooooooooooooooooooooong string
a looong string
an even loooooonger string
a verrrrrrrrry looooooooooooooooooooooong string
```
It looks like it's not even about "whether the buffer is full". It's just some weird fixed 3-times-rule and I totally have no clue where it comes from. I'm now guessing it might be issue with the implementation of this rust io_uring library, or maybe kernel. But I just don't know how to dive deeper. Anyway, this shows a risk that the library will perform some unexpected behaviors in Linux world.

**Context**
The system of the fedora machine is:
OS: Fedora 33,
kernel: 5.9.16-200.fc33.x86_64
CPU: Intel Core i5-7200U

The system of the ubuntu machine is:
OS: Ubuntu 20.10
kernel: 5.8.0-36-generic
CPU: Intel Core i7-4720HQ

I'm not sure if this issue is strange/severe enough to draw your attention to take a look into. If so, I would be grad to help.

**Comment by haruka28** [comment]
For additional info: The same lazy return behavior is observed on Ubuntu 20.10 when the kernel is manually upgraded to 5.11.0-051100rc2-generic. Seems like the issue started somewhere between 5.8.0 and 5.9.16.

**Comment by quininer** [comment]
I believe this is the reserved behavior of kernel. For blocking IO, it is reasonable to return at any time.

You can set fd to nonblocking or use `send`/`recv` to avoid it.

**Comment by JeepYiheihou** [comment]
Changing to use `recv` solved the problem. Thanks.
