### ISSUE TITLE
Connect immediately returns 0, is not connected

### ISSUE THREAD

**Issue by jawline** [tokio-rs/io-uring#54]
Hi,

I created a connection with a TCP socket using the following code:
```
    let poll_e = opcode::Connect::new(
      Fd(new_fd),
      &mut addr as *mut sockaddr_in as *mut sockaddr,
      mem::size_of::<sockaddr_in>() as u32,
    )
    .build()
    .user_data(poll_token as _);
```

Here the event loop immediately acknowledges the connect with a ret of 0, but the socket is not connected yet. Is there any way to defer the Connect opcode until the socket is readable and fully connected?

**Comment by quininer** [comment]
I think you need to use `PollAdd` to do a poll.

**Comment by StephanDollberg** [comment]
Is this even the case with IORING_FEAT_FAST_POLL?

**Comment by jawline** [comment]
Using kernel 5.9.0-0 Debian. If I 'accept' a socket and then do 'recv' I do not need to poll but my problem is that when I connect to an outbound location using 'connect' the cqe comes back immediately with 0 (success?) but I have no way of knowing when it's actually ready / connected.

If I need to PollAdd how would I poll for the connection being established? I probably missed an example where opcode::Connect is used properly.

**Comment by quininer** [comment]
It seems that io_uring will handle `EINPROGRESS` in kernel (see https://github.com/torvalds/linux/blob/v5.9/fs/io_uring.c#L4517). This shouldn't happen.

Can you provide a minimal reproducible example?

**Comment by jawline** [comment]
You're correct - it turns out it was user error. The memory address for addr was being free'd before usage (It's hard to reconcile Rust with CQE's). I've still no idea why connect was returning 0 but if I malloc and free explicitly the problem goes away.

Thanks for the help!
