### ISSUE TITLE
Move unsafety to entry creation

### ISSUE THREAD

**Issue by Koxiaet** [tokio-rs/io-uring#60]
`io_uring` requires at least one unsafe function; currently this is `push` on the submission queue. However moving this unsafety to the creation of the `squeue::Entry`s (in the opcode module) has a few benefits:
- Some operations such as `Nop` can be made fully safe.
- The unsafety is closer to where users will actually have to audit.
- The safety docs will be more helpful. For example, for `Timeout` writing "`timespec` must be a valid pointer for the lifetime of this entry" in `Timeout::new` is clearer than writing "the entry must be valid for the entire operation" in `push`.

**Comment by quininer** [comment]
I don't think this is useful. The only safe entry is `Nop`, `{Poll,Timeout}Remove` and `AsyncCancel`, and `Nop` has almost no meaning in practice.

This crate is a low-level library, and developer must have sufficient knowledge to use it. Just like pointer, it is safe to build it, but it is unsafe to use it.
It is useful to add security docs about `timespec`, and I believe it is worth it.

Move unsafe code is not enough to prevent abuse. for safety abstraction, I think it should be implement in another library. I am planning to pick it up again recently. https://github.com/quininer/ritsu/issues/17

**Comment by Koxiaet** [comment]
> Just like pointer, it is safe to build it, but it is unsafe to use it.

I see, that's a good reason it should stay the way it is. I suppose the entries in this API are more like pointers than they are like references.
