### ISSUE TITLE
Compare to ringbahn

### ISSUE THREAD

**Issue by photoszzt** [tokio-rs/io-uring#63]
There're couple io_uring bindings available in the community. Is there any reason to start another binding effort? Compare to ringbahn, is there anything new in this new binding? Since both repos claim to provide safe API, what's the difference between these two repos in design? I'm not familiar with ringbahn nor tokio's io-uring but I'm interested to know the differences.

**Comment by quininer** [comment]
The library does not provide fully safety API, but aims to provide the most reliable low-level abstraction.

You should compare it with `liburing` or `iou`.

If compared with `iou`, this library started earlier than `iou` and is the only bindings that does not depend on `liburing`.

**Comment by photoszzt** [comment]
I see, so basically, it's a liburing implemented in Rust.
