### ISSUE TITLE
Giving out &mut SubmissionQueue and &mut CompletionQueue is unsound

### ISSUE THREAD

**Issue by Kestrer** [tokio-rs/io-uring#71]
The current API gives out mutable references to the inner `SubmissionQueue` and `CompletionQueue` of the io_uring instance. However this gives the ability for users to replace the queues entirely with a different one, leading to code like this causing unsoundness:

```rust
let mut ring_a = IoUring::new(16)?;
let mut ring_b = IoUring::new(16)?;
mem::swap(ring_a.completion(), ring_b.completion());
drop(ring_a); // ring_a's cq is freed...
let freed_queue = ring_b.completion(); // ...but we can still access it here.
```

I think this is best solved by instead handing out a `CompletionQueueMut`/`cqueue::Mut` type or something like that. I'm working on a fix for this now.

**Comment by quininer** [comment]
Good catch!
