### ISSUE TITLE
io_uring statx doesn't work

### ISSUE THREAD

**Issue by sunyulin728** [tokio-rs/io-uring#83]
I tried to use io_uring statx but fail with errno 22. The same parameters can run successfully with libc::statx directly. 

I didn't find statx sample code or test code. Is there any known issue?

**Comment by quininer** [comment]
I have not been able to reproduce the problem, can you provide the code to reproduce it?

**Comment by quininer** [comment]
I added a test on statx. https://github.com/tokio-rs/io-uring/blob/ef2b1ee230d5f3750d84e908c6fa1c73a4b0401b/io-uring-test/src/tests/fs.rs#L276-L356

**Comment by sunyulin728** [comment]
I think it is my code problem. I will dig into it.

BTW: When I run the test code, I got following error message.

assert_eq!(statxbuf, statxbuf2);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `libc::statx` cannot be formatted using `{:?}` because it doesn't implement `Debug`
    |
    = help: the trait `Debug` is not implemented for `libc::statx`

**Comment by quininer** [comment]
You need to manually turn on the `extra_traits` feature of libc.
