### ISSUE TITLE
TCP Echo example fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by emschwartz** [tokio-rs/io-uring#89]
When I try to run the example on Ubuntu 20.04 (with the linux kernel version 5.4), it produces this error:

```shell
$ cargo run --example tcp_echo                                              ✹
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/tcp_echo`
listen 127.0.0.1:3456
token Some(Accept) error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
token Some(Accept) error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
token Some(Accept) error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
```

FWIW, running the readme example with the fix described in https://github.com/tokio-rs/io-uring/issues/87 worked but it seems that calling `accept` is failing. Any ideas what the issue might be?

**Comment by quininer** [comment]
`accept` is available on the 5.5 kernel.

**Comment by emschwartz** [comment]
Doh :facepalm:

Thanks for the quick response!

**Comment by emschwartz** [comment]
Would it be worth putting the minimum kernel version in the Readme?

**Comment by Darksonn** [comment]
That would be a good idea.
