### ISSUE TITLE
OOM when running test command from README

### ISSUE THREAD

**Issue by Dhs92** [tokio-rs/io-uring#95]
When running `cargo run --package io-uring-test` my system eventually crashes while it's hanging on `test queue_nodrop
`. Looking at htop while running the test I can see my memory usage jump from 4GB to 16GB, 20GB+, then 32GB and the system then crashes due to OOM. Memory usage for the test process shows as 0% in htop.

**Version:** 0.5.1
**Rust version:** rustc 1.56.0-nightly (9c25eb7aa 2021-07-25)
**Kernel version:** 5.13.4-arch1-1

Edit: changed the title to better reflect the issue

**Comment by quininer** [comment]
This test infinite pushes entries into queue until it returns to EBUSY. It sounds like kernel behavior has changed.

https://github.com/tokio-rs/io-uring/blob/master/io-uring-test/src/tests/queue.rs#L120

**Comment by Dhs92** [comment]
Looks like `io_uring_enter(..)` is returning a non-zero value. When running the test through `strace` I am seeing that it is returning `8`

`io_uring_enter(3, 8, 0, 0, NULL, 128)   = 8`

**Comment by quininer** [comment]
This is expected, because the queue capacity is 8, so we always submit every 8 entries.

Kernel 4.13 changed behavior and no longer submitted according to cq limit. this test needs to be fix or remove.

**Comment by Dhs92** [comment]
Ah, looks like I was looking in the wrong place. Thanks
Also, 4.13 or 5.13?

**Comment by quininer** [comment]
5.13, sorry.
